### ISSUE TITLE
Conform Refs

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st430-1#10]
in Norm Refs:
```
Internet Engineering Task Force (IETF) RFC 3066, Tags for the Identification of Languages.
Internet Engineering Task Force (IETF) RFC 3339, Date and Time on the Internet: Timestamps. url: https://www.rfc-editor.org/rfc/rfc3339
Internet Engineering Task Force (IETF) RFC 4122, A Universally Unique IDentifier (UUID) URN Namespace.
Internet Engineering Task Force (IETF) RFC 8017, PKCS #1: RSA Cryptography Specifications Version 2.2.
```
Should be updated to:
```
IETF RFC 3066, Tags for the Identification of Languages. url: https://www.rfc-editor.org/rfc/rfc3066
IETF RFC 3339, Date and Time on the Internet: Timestamps. url: https://www.rfc-editor.org/rfc/rfc3339
IETF RFC 4122, A Universally Unique IDentifier (UUID) URN Namespace. url: https://www.rfc-editor.org/rfc/rfc4122
IETF RFC 8017, PKCS #1: RSA Cryptography Specifications Version 2.2. url: https://www.rfc-editor.org/rfc/rfc8017
```

Citations for these should include the IETF. 

In Bib Refs:
```
FIPS 197, Advanced Encryption Standard (AES).
```
Should be:
```
NIST FIPS 197, Advanced Encryption Standard (AES). url: https://doi.org/10.6028/NIST.FIPS.197
```

**Comment by msheby** [comment]
These changes have been committed.

**Comment by SteveLLamb** [comment]
A few more to add:

Norm Refs
```
W3C XML Schema Part 1: Structures (latest edition). url: http://www.w3.org/TR/xmlschema-1/
W3C XML Signature Syntax and Processing Version 1.1 (latest edition). url: https://www.w3.org/TR/xmldsig-core1/
```
- XML Sig should include the `W3C` in the citation, like `W3C XML 1.0` does. 
- `W3C XML Schema Part 1` is not actually referenced in the prose anywhere. Need to remove or add it into the prose where applicable. 

Bib Ref
```
SMPTE ST 430-12, D-Cinema Operations — FSK Synchronization Signal.
```
- not actually referenced in the prose anywhere. Need to remove or add it into the prose where applicable.

**Comment by msheby** [comment]
Checking for the reason behind the FSK inclusion in 2019's amendment...

**Comment by SteveLLamb** [comment]
> Checking for the reason behind the FSK inclusion in 2019's amendment...

It was because we were doing this at the same time as the other IAB docs and revisions around that project. SMPTE was less strict about Bibliography containing things "for further reading" without being in the prose. The ISO directives, and the SMPTE rules on this has changed since where it must now be in the prose of the document.

**Comment by msheby** [comment]
Committed.

**Comment by msheby** [comment]
Resolved by <https://github.com/SMPTE/st430-1-private/releases/tag/r2023-wd2>.
