### ISSUE TITLE
Clause 4: Formatting abbreviations with sources

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-1#102]
We need to figure out a consistent way to format:

- A term with only an abbreviation. This would usually be listed in a separate "Abbreviations" clause or subclause, but can be included in the Terms and Definitions, with the appropriate heading, e.g., "Terms, Definitions, and Abbreviated Terms"
  Perhaps list as follows, all bold:
  
    **Key Delivery Message**
    **KDM**
- A term with only an abbreviation that cites a source.
  I would format as follows, with the term and its abbreviation in bold:

     **Coordinated Universal Time**
     **UTC**
     [SOURCE: [ISO 8601-1](https://doc.smpte-doc.org/st430-1-private/releases/20230907-pub/#bib-iso-8601-1)]

**Comment by SteveLLamb** [comment]
Adding this comment to https://github.com/SMPTE/html-pub/issues/194 and closing here. This is a larger formatting issue.
