### ISSUE TITLE
TOC (PDF Only): Link to 6.3.10 goes to top of page 13

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-1#11]
Link to 6.3.10 go to top of page 13, instead of to the heading, which is towards the bottom of page 13.

Link works fine in PDF.

**Comment by SteveLLamb** [comment]
I cannot replicate this in either the PDF or HTML, @ERyan71258 can you clarify where this was occurring? In a browser or in a PDF app/preview?

**Comment by ERyan71258** [comment]
Hi Steve,

This was fixed. I should have resolved the comment.

Thanks!

All the best,

Ellen

**Comment by ERyan71258** [comment]
Hi Steve,

This was fixed. I should have resolved the comment.

Thanks!

All the best,

Ellen
