### ISSUE TITLE
TOC; 6.3.9.3, NOTE 2, Sentence 2 (PDF Only): Links to 6.3.10.2 go to top of page 13

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-1#19]
Links to 6.3.10.2 go to top of page 13, instead of to the heading, which is towards the bottom of page 13.

Note that there are two instances in NOTE 2.

Links work fine in PDF.

**Comment by SteveLLamb** [comment]
@ERyan71258, same comment as https://github.com/SMPTE/st430-1/issues/11#issuecomment-2118236205

Also, not seeing a `NOTE 2` in this section. Perhaps already addressed?

**Comment by ERyan71258** [comment]
Hi Steve,

Both links were fixed. I should have resolved the comment.

Thanks!

All the best,

Ellen

**Comment by ERyan71258** [comment]
Meant to close.
