### ISSUE TITLE
incorrect normative reference

### ISSUE THREAD

**Issue by msheby** [SMPTE/st430-1#2]
The references in 5.2.3, 5.2.5.2, and the informative bibliography to ISO 3166 are incorrect; they should instead be to RFC 3066.

Enhancement: the normative reference should be to BCP 47 instead.

**Comment by palemieux** [comment]
RFC 5646 has obsoleted RFC 3066.

**Comment by palemieux** [comment]
> RFC 2253 obsoleted by RFC 4514.

RFC 4514 introduces substantive changes to RFC 2253 (https://datatracker.ietf.org/doc/html/rfc4514#appendix-B), so I do not think we can replace the latter by the former without an extensive study... unless all implementations use RFC 4514.

**Comment by palemieux** [comment]
> RFC 4514 introduces substantive changes to RFC 2253 (https://datatracker.ietf.org/doc/html/rfc4514#appendix-B), so I do not think we can replace the latter by the former without an extensive study... unless all implementations use RFC 4514.

After further research, it looks like the correct reference is the _Distinguished Name Encoding Rules_ section (https://www.w3.org/TR/xmldsig-core1/#dname-encrules) in https://www.w3.org/TR/xmldsig-core1/

**Comment by msheby** [comment]
Resolved by <https://github.com/SMPTE/st430-1-private/releases/tag/r2023-wd1>.
