### ISSUE TITLE
TOC; 7.2.3, Table 6, Row 4, Col 2 (PDF Only): Links to 6.3.9.3 goes to top of page 12

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-1#21]
Links to 6.3.9.3 goes to top of page 12, instead of to the heading, which is in the middle of the page.

Links work fine in PDF.

**Comment by SteveLLamb** [comment]
@ERyan71258, same comment as https://github.com/SMPTE/st430-1/issues/11#issuecomment-2118236205

**Comment by ERyan71258** [comment]
Hi Steve,

This was fixed. I should have resolved the comment.

Thanks!

All the best,

Ellen
