### ISSUE TITLE
6.3.9.3, Table 2 (PDF Only): Missing row

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-1#24]
The second row of Table 2 is cut off in the PDF.

**Comment by SteveLLamb** [comment]
I'm not seeing this. @ERyan71258 perhaps this is resolved?

**Comment by ERyan71258** [comment]
In the original version, the table was missing the second row, as it was at the bottom of the page. It was fixed in the published version.
![image](https://github.com/SMPTE/st430-1/assets/118845840/59c64637-1329-4626-a792-e9e7107691b7)

Ignore the red text - my own annotations.

I found a few instances in the PDFs in which tables that extended over more than one page lost rows.

Consider the issue closed.
