### ISSUE TITLE
missing normative reference?

### ISSUE THREAD

**Issue by msheby** [SMPTE/st430-1#4]
Although one can assume the contents of annex B are an XML schema, one could add a normative reference to be explicit as to which version of the schema language it conforms.

**Comment by palemieux** [comment]
I think we can simply state _XML Schema as referenced in [ETM]_

**Comment by palemieux** [comment]
In fact, it is more complicated: ST 430-1 uses ST 433, which itself references XML schema, but never references ST 433, so it looks like we need to add a reference to ST 433, which removes the need for a reference to/mention of XML Schema.

**Comment by msheby** [comment]
Resolved by <https://github.com/SMPTE/st430-1-private/releases/tag/r2023-wd1>.
