### ISSUE TITLE
subtle ISO 8601 conflict

### ISSUE THREAD

**Issue by msheby** [SMPTE/st430-1#8]
Table 3 uses a time shift string of `-00:00`. In our normative reference, RFC 3339, section 5.6 states that it is a profile of ISO 8601. ISO 8601 in turn states that the time shift "shall be expressed as positive ... if it is ahead of or equal to UTC." We should switch the examples to read `+00:00` instead.

**Comment by palemieux** [comment]
In fact RFC 3339 specifically states that _If the time in UTC is known, but the offset to local time is unknown, this can be represented with an offset of "-00:00"_, which is not the case here.

**Comment by msheby** [comment]
Resolved by <https://github.com/SMPTE/st430-1-private/releases/tag/r2023-wd1>.
